CMAKE_MINIMUM_REQUIRED( VERSION 3.10 )

SET( CMAKE_CXX_STANDARD 11 )
SET( CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}/build/lib )
SET( CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}/build/lib )
SET( CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}/build/bin )

GET_FILENAME_COMPONENT(
	Base_INCLUDE_DIR
	"${CMAKE_CURRENT_LIST_DIR}/base/inc"
	ABSOLUTE )

GET_FILENAME_COMPONENT(
	Base_LIBRARIES
	"${CMAKE_LIBRARY_OUTPUT_DIRECTORY}/libbase.so"
	ABSOLUTE )

if ( NOT EXISTS ${Base_LIBRARIES} AND NOT DEFINED BASE_LIB )
	MESSAGE( FATAL_ERROR "BASE LIB DOES NOT COMPILED" )
endif()
