CMAKE_MINIMUM_REQUIRED( VERSION 3.10 )

SET( CMAKE_CXX_STANDARD 11 )

GET_FILENAME_COMPONENT(
	Base_INCLUDE_DIR
	"${CMAKE_CURRENT_LIST_DIR}/base/inc"
	ABSOLUTE )

GET_FILENAME_COMPONENT(
	Base_LIBRARIES
	"${CMAKE_CURRENT_LIST_DIR}/base/cmake/build/libbase.so"
	ABSOLUTE )

if ( NOT EXISTS ${Base_LIBRARIES} )
	MESSAGE( FATAL_ERROR "BASE LIB DOES NOT COMPILED" )
endif()
